### ISSUE TITLE
How to run this demo

### ISSUE THREAD

**Issue by ccwinner** [Luubra/EmojiIntelligence#2]
I opened the playground, with top status bar shown as "Running EmojiIntelligence", nothing happened.

**Comment by BilalReffas** [comment]
Install the new Xcode update. Sometimes you have to wait or please show me a current screenshot

**Comment by ccwinner** [comment]
![snip20180517_1](https://user-images.githubusercontent.com/10354098/40184118-0402bc9a-5a22-11e8-9cbb-188ba4aa6ba8.png)

**Comment by BilalReffas** [comment]
Watch this video to see how to run a playground on macOS https://www.youtube.com/watch?v=zkUZ2D9sSqo
